version: '3.8'
services:
  atomicai:
    container_name: atomicai
    image: atomicai
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4321:4321
  # rethink:
  #   image: rethinkdb:2.4
  #   ports:
  #     - "8080:8080"
  #     - "28015:28015"
    # volumes:
    #   - rethinkdb:/apps/rethinkdb/data
